name: deploy myblog

on:
  push:
    branches:
      - 'main' # 针对 main 分支
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'bin/*'
      - 'package.json'

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2 # 第三方的 action

      - name: set id_rsa # 设置 id_rsa
        run: |
          mkdir -p ~/.ssh/
          echo "{{secrets.MY_ID_RSA}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # ssh-keyscan 192.168.178.128 >> ~/.ssh/known_hosts
          # chmod 777 known_hosts

